param(
    # Replace an existing codex-CADmcp block that this script generated earlier (e.g. after moving the install).
    [switch]$Force,
    # Path of cad-super-mcp.exe (default: this checkout's .venv-gateway).
    [string]$Gateway = ""
)

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "_common.ps1")
$Root = Split-Path -Parent $PSScriptRoot
if (-not $Gateway) { $Gateway = Join-Path $Root ".venv-gateway\Scripts\cad-super-mcp.exe" }
$Config = Join-Path $env:USERPROFILE ".cad-super-mcp\config.json"
$CodexDir = if ($env:CODEX_HOME) { $env:CODEX_HOME } else { Join-Path $env:USERPROFILE ".codex" }
$CodexConfig = Join-Path $CodexDir "config.toml"
$Marker = "# CAD Super MCP - generated by register-codex.ps1"

if (-not (Test-Path $Gateway)) { throw "Gateway not installed: $Gateway. Run scripts\install.ps1 first." }
if (-not (Test-Path $Config)) { throw "CAD Super config not found: $Config" }
New-Item -ItemType Directory -Force -Path $CodexDir | Out-Null

$raw = ""
if (Test-Path $CodexConfig) { $raw = [System.IO.File]::ReadAllText($CodexConfig) }
$header = '(?m)^\[mcp_servers\.codex-CADmcp\]\s*$'
if ($raw -match $header) {
    if (-not $Force) {
        Write-Host "codex-CADmcp is already registered in $CodexConfig; no changes made. Use -Force to regenerate it (e.g. after moving the install)." -ForegroundColor Yellow
        exit 0
    }
    $generated = '(?ms)^' + [regex]::Escape($Marker) + '\s*\r?\n\[mcp_servers\.codex-CADmcp\].*?(?=^\[(?!mcp_servers\.codex-CADmcp)|\z)'
    if ($raw -notmatch $generated) {
        throw "The existing [mcp_servers.codex-CADmcp] block was not generated by this script; remove or edit it by hand in $CodexConfig, then run this again."
    }
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    Copy-Item $CodexConfig "$CodexConfig.bak-$stamp"
    Write-Host "Backup: $CodexConfig.bak-$stamp" -ForegroundColor DarkGray
    $raw = [regex]::Replace($raw, $generated, "").TrimEnd()
    Write-Utf8NoBom -Path $CodexConfig -Text ($raw + "`r`n")
} elseif (Test-Path $CodexConfig) {
    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    Copy-Item $CodexConfig "$CodexConfig.bak-$stamp"
    Write-Host "Backup: $CodexConfig.bak-$stamp" -ForegroundColor DarkGray
} else {
    New-Item -ItemType File -Force -Path $CodexConfig | Out-Null
}

$g = ConvertTo-TomlString $Gateway
$c = ConvertTo-TomlString $Config
$block = "`r`n$Marker`r`n[mcp_servers.codex-CADmcp]`r`ncommand = $g`r`nenabled = true`r`nstartup_timeout_sec = 30`r`ntool_timeout_sec = 240`r`ndefault_tools_approval_mode = `"writes`"`r`n`r`n[mcp_servers.codex-CADmcp.env]`r`nCAD_SUPER_CONFIG = $c`r`n"
Add-Utf8NoBom -Path $CodexConfig -Text $block
Write-Host "Registered codex-CADmcp in: $CodexConfig" -ForegroundColor Green
Write-Host "Fully restart Codex, then run /mcp and confirm codex-CADmcp is connected." -ForegroundColor Cyan
